// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iubrozwfoqkhlwckaxxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1YnJvendmb3FraGx3Y2theHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTc1MDMsImV4cCI6MjA3MjA3MzUwM30.8sMLoLtMlhNcRsjOy0x1WIudnSHe1hyaXuZaJERAUWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});